"""Add clinician_summary to analysis_translations

Revision ID: 0d9c40325c4d
Revises: 75dbea6aaf06
Create Date: 2026-10-03 11:17:49.116498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0d9c40325c4d'
down_revision: Union[str, None] = '75dbea6aaf06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('actor_admin_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('admin_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('assigned_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinician_summary', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_analysis_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('medications_json',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('doctor_discussion_points',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('chat_session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('chat_safety_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('chat_session_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('help_article_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('incident_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('actor_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('llm_diagnostic_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.alter_column('embedding_json',
               existing_type=sa.NUMERIC(precision=768),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('report_analyses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('structured_lab_values',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('entities',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('abnormal_findings',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('model_versions',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('report_translations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('sensitive_access_grants', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('admin_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('approved_by_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('support_ticket_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('ticket_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_help_articles', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('attached_by',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('ticket_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('assigned_admin_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('related_report_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('related_incident_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.alter_column('related_incident_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('related_report_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('assigned_admin_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_messages', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('ticket_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_help_articles', schema=None) as batch_op:
        batch_op.alter_column('attached_by',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('ticket_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_events', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('sensitive_access_grants', schema=None) as batch_op:
        batch_op.alter_column('approved_by_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('admin_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('report_translations', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('report_analyses', schema=None) as batch_op:
        batch_op.alter_column('model_versions',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('abnormal_findings',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('entities',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('structured_lab_values',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('report_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.alter_column('embedding_json',
               existing_type=sa.JSON(),
               type_=sa.NUMERIC(precision=768),
               existing_nullable=True)
        batch_op.alter_column('report_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('medication_schedules', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('report_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('medical_profiles', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('llm_diagnostic_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_by_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.alter_column('actor_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('incident_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('help_article_versions', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('chat_safety_events', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('chat_session_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('chat_session_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.alter_column('doctor_discussion_points',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('medications_json',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('report_analysis_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('clinician_summary')

    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('admin_role_permissions', schema=None) as batch_op:
        batch_op.alter_column('permission_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('role_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('admin_role_assignments', schema=None) as batch_op:
        batch_op.alter_column('assigned_by_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('role_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('admin_permissions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('actor_admin_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
