"""Add MFA replay protection fields

Revision ID: 364c2879206d
Revises: 855923c2295c
Create Date: 2026-10-01 23:13:15.540715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364c2879206d'
down_revision: Union[str, None] = '855923c2295c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_mfa_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_mfa_jti', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_mfa_jti')
        batch_op.drop_column('last_mfa_time')

    # ### end Alembic commands ###
