"""Add notifications and chat models

Revision ID: 40f600dd76df
Revises: e7de42c7d83c
Create Date: 2026-08-31 08:52:24.289371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '40f600dd76df'
down_revision: Union[str, None] = 'e7de42c7d83c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_translations')
    op.drop_index(op.f('ix_knowledge_chunks_content_hash'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.alter_column('medical_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('medical_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('reports', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('medical_profiles', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('medical_profiles', 'id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_hash', sa.VARCHAR(), nullable=False),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_content_hash'), 'knowledge_chunks', ['content_hash'], unique=1)
    op.create_table('analysis_translations',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('report_analysis_id', sa.CHAR(length=32), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('patient_summary', sa.TEXT(), nullable=False),
    sa.Column('findings_json', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_analysis_id'], ['report_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_analysis_id', 'language', name=op.f('_report_lang_uc'))
    )
    # ### end Alembic commands ###
