"""make expires_at nullable on SensitiveAccessGrant

Revision ID: 715e4f09cea7
Revises: c8164468277c
Create Date: 2026-09-24 16:45:27.214301

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "715e4f09cea7"
down_revision: Union[str, None] = "c8164468277c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensitive_access_grants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("approved_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("revoker_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("revoke_reason", sa.Text(), nullable=True))
        batch_op.alter_column("expires_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_sensitive_access_grants_status"), ["status"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_sensitive_access_grants_revoker_id",
            "users",
            ["revoker_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensitive_access_grants", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_sensitive_access_grants_revoker_id", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_sensitive_access_grants_status"))
        batch_op.alter_column("expires_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_column("revoke_reason")
        batch_op.drop_column("revoker_id")
        batch_op.drop_column("approved_at")

    with op.batch_alter_table("system_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_settings_key"))

    op.drop_table("system_settings")
    with op.batch_alter_table("privacy_data_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_privacy_data_requests_user_id"))
        batch_op.drop_index(batch_op.f("ix_privacy_data_requests_status"))

    op.drop_table("privacy_data_requests")
    op.drop_table("maintenance_mode")
    with op.batch_alter_table("feature_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feature_flags_name"))

    op.drop_table("feature_flags")
    with op.batch_alter_table("announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_announcements_status"))

    op.drop_table("announcements")
    # ### end Alembic commands ###
