"""Add mfa_challenges and last_totp_counter

Revision ID: 7b7135d1f49f
Revises: 364c2879206d
Create Date: 2026-10-02 00:01:44.444959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7135d1f49f'
down_revision: Union[str, None] = '364c2879206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_challenges',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_challenges_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_totp_counter', sa.Integer(), nullable=True))
        batch_op.drop_column('last_mfa_time')
        batch_op.drop_column('last_mfa_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_mfa_jti', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_mfa_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_totp_counter')

    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_challenges_user_id'))

    op.drop_table('mfa_challenges')
    # ### end Alembic commands ###
