"""Add mfa_challenges and last_totp_counter

Revision ID: 7b7135d1f49f
Revises: 364c2879206d
Create Date: 2026-10-02 00:01:44.444959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7135d1f49f'
down_revision: Union[str, None] = '364c2879206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_challenges',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_challenges_user_id'), ['user_id'], unique=False)

    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('help_article_versions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=True)

    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('support_ticket_help_articles', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_totp_counter', sa.Integer(), nullable=True))
        batch_op.drop_column('last_mfa_time')
        batch_op.drop_column('last_mfa_jti')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_mfa_jti', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('last_mfa_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_totp_counter')

    with op.batch_alter_table('support_ticket_help_articles', schema=None) as batch_op:
        batch_op.alter_column('article_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('job_executions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('help_articles', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('help_article_versions', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('article_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    op.create_table('_alembic_tmp_users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=9), nullable=False),
    sa.Column('preferred_language', sa.VARCHAR(), nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mfa_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mfa_challenges_user_id'))

    op.drop_table('mfa_challenges')
    # ### end Alembic commands ###
