"""make report_id nullable in medication_schedules

Revision ID: 7cbdc4385fff
Revises: 7e3beb14fd49
Create Date: 2026-09-23 10:15:26.676421

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cbdc4385fff"
down_revision: Union[str, None] = "7e3beb14fd49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medication_schedules") as batch_op:
        batch_op.alter_column(
            "report_id", existing_type=sa.CHAR(length=32), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medication_schedules") as batch_op:
        batch_op.alter_column(
            "report_id", existing_type=sa.CHAR(length=32), nullable=False
        )
    # ### end Alembic commands ###
