"""Add provider and model to report analysis

Revision ID: 7e3beb14fd49
Revises: a23405120928
Create Date: 2026-09-22 11:20:10.022837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3beb14fd49'
down_revision: Union[str, None] = 'a23405120928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_analyses', sa.Column('llm_provider', sa.Text(), nullable=True))
    op.add_column('report_analyses', sa.Column('llm_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_analyses', 'llm_model')
    op.drop_column('report_analyses', 'llm_provider')
    # ### end Alembic commands ###
