"""Add verification_status to report_analysis

Revision ID: a23405120928
Revises: a749cedb8708
Create Date: 2026-09-19 09:13:23.368440

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a23405120928"
down_revision: Union[str, None] = "a749cedb8708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_analyses", sa.Column("verification_status", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_analyses", "verification_status")
    # ### end Alembic commands ###
