"""Add MFA fields to User

Revision ID: ae860ecd3511
Revises: 9858814da870
Create Date: 2026-10-01 22:57:29.171639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae860ecd3511'
down_revision: Union[str, None] = '9858814da870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mfa_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mfa_recovery_codes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_recovery_codes')
        batch_op.drop_column('mfa_secret')
        batch_op.drop_column('mfa_enabled')
    # ### end Alembic commands ###
