"""add ui_labels to analysis_translations

Revision ID: b1ed74e24981
Revises: a21f77430a92
Create Date: 2026-09-27 20:33:41.394179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ed74e24981'
down_revision: Union[str, None] = 'a21f77430a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_labels', sa.JSON(), nullable=True, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.drop_column('ui_labels')

    # ### end Alembic commands ###
