"""Add knowledge document and chat safety models

Revision ID: c8164468277c
Revises: ace1590fc209
Create Date: 2026-09-23 21:33:23.199693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8164468277c'
down_revision: Union[str, None] = 'ace1590fc209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'archived', name='doclifecyclestatus'), nullable=False),
    sa.Column('approval_state', sa.String(length=100), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_safety_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=False),
    sa.Column('action_taken', sa.String(length=100), nullable=False),
    sa.Column('safe_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_document_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('report_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.create_foreign_key('fk_rag_chunks_knowledge_document_id', 'knowledge_documents', ['knowledge_document_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rag_chunks_knowledge_document_id', type_='foreignkey')
        batch_op.alter_column('report_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)
        batch_op.drop_column('knowledge_document_id')

    op.drop_table('chat_safety_events')
    op.drop_table('knowledge_documents')
    # ### end Alembic commands ###
