"""add medications_json

Revision ID: dd7a0d153610
Revises: b1ed74e24981
Create Date: 2026-09-27 21:06:44.706908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'dd7a0d153610'
down_revision: Union[str, None] = 'b1ed74e24981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medications_json', sa.JSON(), nullable=True, server_default='[]'))
        batch_op.alter_column('ui_labels',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_translations', schema=None) as batch_op:
        batch_op.alter_column('ui_labels',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.drop_column('medications_json')

    # ### end Alembic commands ###
