import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../services/api_models.dart';

/// ExportService — generates a clean PDF from a ReportAnalysisModel
/// and either shares it or opens the system print dialog.
class ExportService {
  ExportService._();
  static final ExportService instance = ExportService._();

  // Primary color
  static const _primary = PdfColor.fromInt(0xFF1A73E8);
  static const _danger = PdfColor.fromInt(0xFFE53935);
  static const _warning = PdfColor.fromInt(0xFFF5A623);
  static const _success = PdfColor.fromInt(0xFF00C48C);
  static const _textDark = PdfColor.fromInt(0xFF0D1117);
  static const _textMuted = PdfColor.fromInt(0xFF5A6472);
  static const _divider = PdfColor.fromInt(0xFFE8ECF0);

  PdfColor _flagColor(String flag) {
    switch (flag) {
      case 'high':
        return _danger;
      case 'low':
        return _warning;
      default:
        return _success;
    }
  }

  Future<pw.Document> _buildDocument({
    required ReportAnalysisModel analysis,
    required String reportTitle,
    required String reportDate,
  }) async {
    final doc = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();
    final fontMono = await PdfGoogleFonts.jetBrainsMonoRegular();

    final baseStyle = pw.TextStyle(font: font, fontSize: 11, color: _textDark);
    final mutedStyle = pw.TextStyle(font: font, fontSize: 10, color: _textMuted);
    final boldStyle = pw.TextStyle(font: fontBold, fontSize: 11, color: _textDark);
    final headStyle = pw.TextStyle(font: fontBold, fontSize: 14, color: _primary);
    final monoStyle = pw.TextStyle(font: fontMono, fontSize: 10, color: _textDark);

    pw.Widget sectionHeader(String title) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.SizedBox(height: 18),
            pw.Text(title, style: headStyle),
            pw.Divider(color: _divider, thickness: 1),
            pw.SizedBox(height: 6),
          ],
        );

    pw.Widget flagBadge(String flag) {
      final color = _flagColor(flag);
      return pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 2),
        decoration: pw.BoxDecoration(
          color: color,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(100)),
        ),
        child: pw.Text(
          flag.toUpperCase(),
          style: pw.TextStyle(font: fontBold, fontSize: 8, color: PdfColors.white),
        ),
      );
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('MedNarrate', style: pw.TextStyle(font: fontBold, fontSize: 20, color: _primary)),
                pw.Text('Medical Report Summary', style: mutedStyle),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Text(reportTitle, style: pw.TextStyle(font: fontBold, fontSize: 13, color: _textDark)),
            pw.Text('Date: $reportDate', style: mutedStyle),
            pw.Divider(color: _primary, thickness: 1.5),
            pw.SizedBox(height: 4),
          ],
        ),
        footer: (_) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.center,
          children: [
            pw.Text(
              'Generated by MedNarrate  |  Not a substitute for professional medical advice',
              style: pw.TextStyle(font: font, fontSize: 8, color: _textMuted),
            ),
          ],
        ),
        build: (context) => [
          // Patient Summary
          if (analysis.patientSummary != null && analysis.patientSummary!.isNotEmpty) ...[
            sectionHeader('Plain Language Summary'),
            pw.Text(analysis.patientSummary!, style: baseStyle),
          ],

          // Clinician Summary
          if (analysis.clinicianSummary != null && analysis.clinicianSummary!.isNotEmpty) ...[
            sectionHeader('Clinical Summary'),
            pw.Text(analysis.clinicianSummary!, style: baseStyle),
          ],

          // Lab Results
          if (analysis.structuredLabValues.isNotEmpty) ...[
            sectionHeader('Lab Results'),
            pw.TableHelper.fromTextArray(
              headers: ['Test', 'Value', 'Unit', 'Ref Low', 'Ref High', 'Status'],
              data: analysis.structuredLabValues.map((lv) => [
                lv.testName,
                lv.value.toString(),
                lv.unit,
                lv.refLow?.toString() ?? '—',
                lv.refHigh?.toString() ?? '—',
                lv.flag.toUpperCase(),
              ]).toList(),
              headerStyle: boldStyle,
              cellStyle: monoStyle,
              headerDecoration: const pw.BoxDecoration(color: _primary),
              headerCellDecoration: const pw.BoxDecoration(color: _primary),
              oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey100),
            ),
          ],

          // Abnormal Findings
          if (analysis.abnormalFindings.isNotEmpty) ...[
            sectionHeader('Abnormal Findings'),
            ...analysis.abnormalFindings.map((f) => pw.Container(
                  margin: const pw.EdgeInsets.only(bottom: 8),
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: _danger, width: 0.5),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
                  ),
                  child: pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Expanded(
                        child: pw.Text(
                          '${f['test_name']} — ${f['value']} ${f['unit']}',
                          style: boldStyle,
                        ),
                      ),
                      flagBadge(f['flag']?.toString() ?? 'normal'),
                    ],
                  ),
                )),
          ],

          // Entities
          if (analysis.entities.isNotEmpty) ...[
            sectionHeader('Medical Entities Detected'),
            pw.Wrap(
              spacing: 8,
              runSpacing: 6,
              children: analysis.entities.map((e) => pw.Container(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.blue50,
                      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(100)),
                    ),
                    child: pw.Text(
                      '${e['word'] ?? ''} (${e['entity_group'] ?? ''})',
                      style: pw.TextStyle(font: font, fontSize: 9, color: _primary),
                    ),
                  )).toList(),
            ),
          ],

          // Evidence Sources
          if (analysis.evidenceSources.isNotEmpty) ...[
            sectionHeader('Evidence Sources (RAG)'),
            ...analysis.evidenceSources.map((src) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 6),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Finding: ${src.finding}', style: boldStyle),
                      pw.Text('Sources: ${src.sources.join(', ')}', style: mutedStyle),
                    ],
                  ),
                )),
          ],

          pw.SizedBox(height: 20),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.orange50,
              border: pw.Border.all(color: _warning),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Text(
              '⚠ DISCLAIMER: This analysis is AI-generated and for informational purposes only. '
              'It does not constitute medical advice. Please consult a qualified healthcare professional '
              'before making any health decisions.',
              style: pw.TextStyle(font: font, fontSize: 9, color: _textDark),
            ),
          ),
        ],
      ),
    );

    return doc;
  }

  /// Share the report as a PDF via the native share sheet.
  Future<void> shareSummaryPdf({
    required ReportAnalysisModel analysis,
    required String reportTitle,
    required String reportDate,
  }) async {
    final doc = await _buildDocument(
      analysis: analysis,
      reportTitle: reportTitle,
      reportDate: reportDate,
    );
    final bytes = await doc.save();

    if (kIsWeb) {
      await Printing.layoutPdf(onLayout: (_) async => bytes);
      return;
    }

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/MedNarrate_Summary.pdf');
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: 'MedNarrate — $reportTitle Summary',
    );
  }

  /// Open the system print/preview dialog (works on web too via printing package).
  Future<void> printSummary({
    required ReportAnalysisModel analysis,
    required String reportTitle,
    required String reportDate,
  }) async {
    final doc = await _buildDocument(
      analysis: analysis,
      reportTitle: reportTitle,
      reportDate: reportDate,
    );
    await Printing.layoutPdf(onLayout: (_) async => await doc.save());
  }
}
