/// Collection of 366 unique, medically safe, general wellness and health tips.
///
/// Designed to provide one unique tip per calendar day with zero repetition
/// across 365 days (and 366 in leap years).
const List<String> kHealthTips = [
  'Drink a full glass of water first thing in the morning to kickstart hydration.',
  'Sip water continuously throughout the day rather than drinking large amounts all at once.',
  'Drink a glass of water 30 minutes before meals to support optimal digestion.',
  'Keep a refillable water bottle with you to track daily fluid intake easily.',
  'Increase your fluid intake on warm days or when engaging in physical activity.',
  'Check your urine color: pale yellow indicates healthy and proper hydration.',
  'Drink extra water when consuming caffeinated beverages to maintain fluid balance.',
  'Infuse water with cucumber, lemon, or mint for a refreshing sugar-free flavor.',
  'Drink water after taking morning medications to ensure smooth swallowing and absorption.',
  'Drink a glass of water after exercising to replace fluids lost through sweat.',
  'Choose plain water over sugary sodas or energy drinks to stay hydrated safely.',
  'Keep water by your bedside to stay hydrated if you wake up thirsty during the night.',
  'Drink warm water or herbal tea to soothe an upset stomach and support digestion.',
  'Hydrate well before starting outdoor activities in hot or humid weather.',
  'Drink water when experiencing mild headaches, as dehydration is a common trigger.',
  'Monitor fluid intake closely during illness, especially if experiencing fever or vomiting.',
  'Avoid excessive iced water during heavy meals if it causes stomach discomfort.',
  'Drink water after consuming salty foods to help your kidneys flush out excess sodium.',
  'Pair every cup of coffee with a small glass of water to keep fluid levels balanced.',
  'Establish a consistent hydration routine by drinking water at fixed times daily.',
  'Drink plenty of water when traveling, as airplane cabin air accelerates dehydration.',
  'Hydrate properly before and after getting a routine blood test or medical draw.',
  'Choose coconut water or electrolyte solutions after intense workouts lasting over an hour.',
  'Drink water before feeling thirsty, as thirst is a sign that dehydration has already begun.',
  'Carry water when running errands to avoid relying on sugary convenience drinks.',
  'Drink water after swimming or water sports to replenish fluids lost in heat.',
  'Rinse your mouth with water after consuming acidic foods to protect tooth enamel.',
  'Drink warm lemon water in the morning to stimulate gut motility and digestion.',
  'Track your daily fluid intake using a journal or health app if prescribed by your doctor.',
  'Consult your physician regarding fluid intake limits if you have kidney or heart conditions.',
  'Fill half your plate with colorful vegetables at lunch and dinner for essential vitamins.',
  'Eat slowly and chew thoroughly to improve digestion and prevent overeating.',
  'Include lean proteins like chicken, fish, beans, or tofu in your daily meals.',
  'Choose whole grains like oats, brown rice, and quinoa over refined white grains.',
  'Limit processed foods high in artificial additives, excess sodium, and trans fats.',
  'Read nutrition labels carefully to check for hidden sugars and elevated sodium levels.',
  'Cook meals at home using fresh ingredients to maintain control over nutritional quality.',
  'Include a source of healthy fat, such as olive oil or avocado, in daily meals.',
  'Eat a balanced breakfast containing protein and fiber to maintain steady energy.',
  'Avoid skipping meals to prevent blood sugar dips and subsequent overeating.',
  'Limit intake of ultra-processed snacks by replacing them with fresh fruit or nuts.',
  'Control portion sizes by using smaller plates and bowls during mealtime.',
  'Eat fatty fish like salmon or mackerel twice a week for heart-healthy omega-3s.',
  'Incorporate plant-based meals into your weekly menu to boost fiber and antioxidants.',
  'Avoid eating heavy or greasy meals right before bedtime to prevent acid reflux.',
  'Steam or bake vegetables instead of deep-frying to retain nutrients and reduce calories.',
  'Season foods with herbs and spices like garlic, ginger, and turmeric instead of salt.',
  'Eat fermented foods like yogurt or kefir to support a healthy gut microbiome.',
  'Swap sugary desserts for fresh berries or a small piece of dark chocolate.',
  'Limit refined sugar consumption to lower the risk of metabolic and dental issues.',
  'Keep raw cut vegetables like carrots and cucumbers ready for convenient snacking.',
  'Choose whole fruits instead of fruit juices to benefit from essential dietary fiber.',
  'Include iron-rich foods such as spinach, lentils, and lean meat in your diet.',
  'Pair iron-rich plant foods with vitamin C sources like citrus to boost absorption.',
  'Limit trans fats by avoiding hydrogenated oils found in processed baked goods.',
  'Incorporate raw, unsalted nuts like almonds and walnuts into your daily diet.',
  'Eat foods rich in potassium, such as bananas and sweet potatoes, to support blood pressure.',
  'Avoid drinking alcohol on an empty stomach to prevent blood sugar crashes.',
  'Choose low-sodium canned foods or rinse canned beans before cooking to remove salt.',
  'Include calcium-rich foods like dairy, fortified plant milk, or leafy greens daily.',
  'Eat regular meals at consistent times each day to stabilize your metabolic rate.',
  'Snack on high-protein foods like Greek yogurt or boiled eggs between meals.',
  'Limit consumption of processed red meats such as sausages, bacon, and hot dogs.',
  'Eat zinc-rich foods like pumpkin seeds and lentils to support immune function.',
  'Avoid distraction like watching television while eating to practice mindful portion control.',
  'Incorporate chia seeds or flaxseeds into oatmeal or smoothies for added fiber.',
  'Choose unrefined, cold-pressed oils for cooking at low to medium heat settings.',
  'Avoid store-bought salad dressings that often contain hidden sugars and preservatives.',
  'Eat dark leafy greens like kale, spinach, and Swiss chard multiple times weekly.',
  'Plan your weekly meals ahead of time to make healthier grocery choices.',
  'Aim for at least 150 minutes of moderate aerobic exercise like brisk walking each week.',
  'Take a 10-minute walk after meals to help lower post-meal blood sugar levels.',
  'Perform strength training exercises twice a week to maintain muscle and bone mass.',
  'Always stretch gently after workouts to improve flexibility and prevent muscle soreness.',
  'Warm up with light cardio for 5 minutes before starting any intense exercise routine.',
  'Take the stairs instead of the elevator whenever possible to build daily movement.',
  'Break up long periods of sitting by standing up and moving every 30 to 60 minutes.',
  'Wear supportive, well-fitting athletic shoes during exercise to protect your joints.',
  'Listen to your body during workouts and stop immediately if you feel sharp pain.',
  'Incorporate balance exercises like standing on one foot to prevent falls as you age.',
  'Maintain proper form during strength training rather than lifting excessively heavy weights.',
  'Walk briskly enough to raise your heart rate while still being able to hold a conversation.',
  'Engage in low-impact exercises like swimming or cycling if you experience joint discomfort.',
  'Cool down with slow walking and deep breathing at the end of a vigorous workout.',
  'Schedule physical activity like an important appointment so it becomes a daily habit.',
  'Use a pedometer or fitness tracker to aim for a daily step goal suited to your health level.',
  'Engage in outdoor activities to combine physical exercise with natural sunlight.',
  'Perform pelvic floor exercises daily to support core stability and bladder health.',
  'Vary your exercise routine to challenge different muscle groups and prevent burnout.',
  'Avoid high-intensity exercise right before sleep if it disrupts your sleep quality.',
  'Keep hand weights or resistance bands near your desk for short exercise breaks.',
  'Include bodyweight exercises like squats, push-ups, and lunges in your home routine.',
  'Stay consistent with physical activity even on busy days by doing brief 10-minute sessions.',
  'Consult your physician before starting a new exercise regimen if you have health conditions.',
  'Avoid exercising in extreme heat or humidity without proper cooling and hydration.',
  'Track your fitness progress through how you feel rather than relying solely on scale weight.',
  'Perform gentle wrist and ankle rolls before sports to reduce risk of sprains.',
  'Incorporate lateral movements like side steps into workouts to strengthen stabilizer muscles.',
  'Use proper lifting techniques, bending at the knees rather than curving your back.',
  'Include active recovery days with gentle walking or light stretching between intense workouts.',
  'Practice yoga or tai chi to enhance flexibility, joint mobility, and mental focus.',
  'Keep proper posture while running: land softly on midfoot and relax your shoulders.',
  'Wipe down gym equipment before and after use to maintain hygiene and prevent germs.',
  'Ramp up workout intensity gradually week by week to prevent overuse injuries.',
  'Exercise with a workout partner to increase accountability and maintain consistency.',
  'Maintain a consistent sleep schedule by going to bed and waking up at the same times daily.',
  'Aim for 7 to 9 hours of quality, uninterrupted sleep every single night.',
  'Keep your bedroom cool, quiet, and dark to promote deeper and more restful sleep.',
  'Turn off electronic screens like smartphones and TVs at least 1 hour before bedtime.',
  'Avoid consuming caffeinated drinks like coffee or energy drinks after 2:00 PM.',
  'Create a relaxing bedtime routine like reading a book or listening to soft music.',
  'Reserve your bed exclusively for sleep and rest, not for working or watching TV.',
  'Expose your eyes to natural sunlight early in the morning to regulate circadian rhythm.',
  'Avoid heavy meals, alcohol, and nicotine in the hours leading up to bedtime.',
  'Use blackout curtains or an eye mask if ambient room light disrupts your sleep.',
  'Choose a supportive mattress and pillow that align your head, neck, and spine.',
  'If unable to sleep after 20 minutes, get up and do a quiet activity in low light.',
  'Limit afternoon naps to 20 or 30 minutes so they do not interfere with night sleep.',
  'Avoid checking the clock repeatedly if you wake up during the middle of the night.',
  'Air out your bedroom daily by opening windows to ensure fresh circulation for sleep.',
  'Wash your bed linens in hot water weekly to remove allergens, dust mites, and sweat.',
  'Use earplugs or a white noise machine if background noise keeps you awake.',
  'Avoid intense exercise within 2 to 3 hours of bedtime to allow your body to cool down.',
  'Wear loose, breathable sleepwear made of natural fibers like cotton.',
  'Keep pets off the bed if they disrupt your sleep or trigger night allergies.',
  'Take a warm bath or shower before bed to relax tense muscles and cue sleep readiness.',
  'Practice deep abdominal breathing when lying in bed to calm your nervous system.',
  'Dim indoor lights an hour before bedtime to stimulate natural melatonin production.',
  'Avoid drinking excessive fluids late in the evening to reduce night bathroom visits.',
  'Address persistent snoring or gasping for air with a doctor to check for sleep apnea.',
  'Keep electrical equipment and glowing light indicators away from your bed area.',
  'Avoid relying on alcohol as a sleep aid, as it impairs deep sleep architecture.',
  'Maintain comfortable bedroom humidity levels using a humidifier or dehumidifier.',
  'Replace your pillows every 1 to 2 years to maintain proper neck support and hygiene.',
  'Keep a notepad by your bed to write down lingering thoughts instead of worrying in bed.',
  'Get morning daylight exposure for at least 15 minutes to strengthen your body clock.',
  'Stick to your sleep routine on weekends to avoid social jetlag on Monday morning.',
  'Avoid taking unprescribed sleeping aids for extended periods without medical advice.',
  'Limit liquid intake 1 to 2 hours before bed if nighttime urination frequently wakes you.',
  'Ensure adequate daytime physical activity to promote natural sleep drive at night.',
  'Brush your teeth thoroughly twice daily for two full minutes using fluoride toothpaste.',
  'Floss between your teeth every day to remove plaque and food debris toothbrush misses.',
  'Replace your toothbrush every 3 to 4 months or sooner if the bristles become frayed.',
  'Follow the 20-20-20 rule when looking at screens: every 20 minutes look 20 feet away for 20 seconds.',
  'Clean your tongue gently daily with a scraper or brush to reduce oral bacteria.',
  'Wear sunglasses offering 100% UV protection when spending time outdoors in sunlight.',
  'Schedule regular dental checkups and professional cleanings every 6 months.',
  'Limit sugary snacks and carbonated soft drinks to protect your tooth enamel from decay.',
  'Adjust screen brightness and contrast so reading does not cause eye strain or fatigue.',
  'Never go to sleep with makeup on, as it can block skin pores and irritate the eyes.',
  'Position your computer monitor at eye level about an arm’s length away from your face.',
  'Use lubricated artificial tears if you experience dry eyes during prolonged computer use.',
  'Do not rub your eyes forcefully with unwashed hands to avoid corneal irritation and infection.',
  'Remove contact lenses before sleeping or swimming unless specifically prescribed for overnight use.',
  'Rinse your mouth with water after eating sweet or acidic foods when brushing is not possible.',
  'Clean contact lenses only with sterile disinfectant solution, never with tap water.',
  'Use a mouthguard during contact sports to protect your teeth and jaw from impact injuries.',
  'Ensure proper indoor lighting when reading or doing fine work to avoid straining your eyes.',
  'Schedule comprehensive eye examinations every 1 to 2 years to check vision and eye pressure.',
  'Rinse your mouth after using steroid inhalers to prevent oral fungal infection (thrush).',
  'Avoid using toothpicks aggressively as they can damage delicate gum tissue and enamel.',
  'Choose soft-bristled toothbrushes to prevent gum recession and enamel wear.',
  'Blink frequently when looking at digital screens to keep the surface of your eyes moist.',
  'Eat foods rich in lutein and zeaxanthin like spinach and corn to support macula eye health.',
  'Avoid smoking or tobacco use, which significantly increases the risk of gum disease and oral cancer.',
  'Wait 30 minutes after eating acidic foods before brushing teeth to avoid eroding softened enamel.',
  'Clean your contact lens storage case daily with sterile solution and replace it every 3 months.',
  'Wear protective safety goggles when using power tools, lawn mowers, or strong chemicals.',
  'Choose sugar-free gum containing xylitol after meals to stimulate saliva and fight decay.',
  'Inspect your gums regularly: healthy gums should appear pink, firm, and should not bleed easily.',
  'Consult your dentist promptly if you notice persistent bad breath, bleeding gums, or tooth sensitivity.',
  'Keep hand towels clean and refrain from sharing eye makeup to prevent pink eye (conjunctivitis).',
  'Ensure adequate lighting behind digital screens to minimize stark glare and eye fatigue.',
  'Include omega-3 fatty acids in your diet to support healthy tear film and reduce dry eye symptoms.',
  'Store your toothbrush in an upright position where it can air dry completely between uses.',
  'Wash your hands with soap and running water for at least 20 seconds before eating.',
  'Wash hands thoroughly after using the restroom, coughing, sneezing, or blowing your nose.',
  'Use alcohol-based hand sanitizer with at least 60% alcohol when soap and water are unavailable.',
  'Cover your mouth and nose with a tissue or your inner elbow when coughing or sneezing.',
  'Avoid touching your face, eyes, nose, and mouth with unwashed hands to stop germ transmission.',
  'Disinfect frequently touched surfaces like door handles, light switches, and phone screens daily.',
  'Wash your hands thoroughly after handling garbage, soil, or cleaning household surfaces.',
  'Clean household sponges and dishcloths frequently or replace them every two weeks.',
  'Wash fresh fruits and vegetables under cold running tap water before preparing or eating them.',
  'Keep raw meat, poultry, and seafood separate from ready-to-eat foods to prevent cross-contamination.',
  'Use separate cutting boards for raw meats and produce to prevent bacterial contamination.',
  'Cook foods, especially poultry and ground meats, to safe internal temperatures verified by a thermometer.',
  'Refrigerate perishable foods within 2 hours of purchase or preparation to halt bacterial growth.',
  'Defrost frozen food safely in the refrigerator, under cold water, or in the microwave—never on the counter.',
  'Wash hands thoroughly after touching pets, animal food, or cleaning pet habitats.',
  'Stay home when sick with contagious symptoms like fever, coughing, or stomach flu to protect others.',
  'Change and wash bath towels every 3 to 4 uses to prevent bacterial growth and skin irritation.',
  'Air out shoes after wearing them and change socks daily to avoid fungal foot infections.',
  'Trim fingernails and toenails regularly, keeping them clean and dry to prevent fungal growth.',
  'Clean your mobile phone screen regularly with an alcohol wipe to remove accumulated bacteria.',
  'Wash workout clothes immediately after exercise to prevent odor-causing bacteria from settling.',
  'Avoid sharing personal items like razors, toothbrushes, towels, or hairbrushes with others.',
  'Keep cuts and scrapes clean, apply antiseptic, and cover with a sterile bandage until healed.',
  'Wash your hands thoroughly after using public transport, shopping carts, or shared equipment.',
  'Store leftover food in airtight containers and consume within 3 to 4 days for optimal food safety.',
  'Check food expiration dates regularly and discard expired items promptly.',
  'Clean kitchen counters with warm soapy water or disinfectant before and after food preparation.',
  'Wear gloves when working with garden soil or household chemicals to protect your skin barrier.',
  'Ensure kitchen trash cans have secure lids and are emptied regularly to deter pests and odors.',
  'Wash bedding in hot water (at least 60°C/140°F) to eradicate dust mites and allergens.',
  'Dry your hands thoroughly after washing, as wet hands transfer bacteria more easily than dry ones.',
  'Clean air conditioning filters and vent covers periodically to maintain healthy indoor air quality.',
  'Avoid touching wounds or medical dressings without washing and drying your hands first.',
  'Sanitize kitchen sinks daily, as moisture and food scraps make them prone to germ buildup.',
  'Keep personal grooming tools like tweezers and nail clippers disinfected with rubbing alcohol.',
  'Take prescribed medications at the exact times specified by your healthcare provider.',
  'Never stop taking a prescribed antibiotic course early, even if you feel completely recovered.',
  'Keep an updated list of all your current medications, dosages, and supplements in your wallet.',
  'Store medications in a cool, dry place away from heat, direct sunlight, and bathroom humidity.',
  'Check expiration dates on all over-the-counter and prescription drugs before taking them.',
  'Use a pill organizer or daily alarm reminders to avoid missing or duplicating medication doses.',
  'Read medication patient information leaflets to understand potential side effects and interactions.',
  'Ask your pharmacist or doctor before taking new over-the-counter drugs alongside your prescriptions.',
  'Never share your prescribed medications with family members or friends under any circumstances.',
  'Dispose of unused or expired medications safely at a pharmacy take-back program or drop box.',
  'Swallow pills with a full glass of water while sitting or standing upright to avoid throat irritation.',
  'Check your blood pressure periodically if recommended by your doctor and record the readings.',
  'Monitor blood sugar levels as directed if you have diabetes or prediabetes.',
  'Know your key health numbers: blood pressure, resting heart rate, cholesterol, and blood glucose.',
  'Schedule annual wellness exams with your primary care physician for routine health evaluation.',
  'Seek immediate medical attention if you experience severe chest pain, sudden numbness, or shortness of breath.',
  'Keep a simple health diary to log symptoms, blood pressure readings, or medication reactions.',
  'Inform your doctor of any herbal remedies, vitamins, or supplements you are currently taking.',
  'Avoid drinking alcohol while taking medications that warn against alcohol interaction.',
  'Store all prescription and over-the-counter medications out of reach and sight of young children.',
  'Take medications with food if instructed, to prevent stomach upset and improve absorption.',
  'Never crush or split sustained-release or enteric-coated tablets unless advised by a pharmacist.',
  'Inspect over-the-counter medicine packaging for intact safety seals before purchasing or consuming.',
  'Keep emergency phone numbers, primary care doctor contacts, and poison control accessible.',
  'Update your medical history and allergy list whenever visiting a new healthcare professional.',
  'Ensure childhood and adult vaccinations, such as tetanus and annual flu shots, are up to date.',
  'Schedule recommended health screenings such as mammograms, colonoscopies, or pap smears on time.',
  'Report unusual symptoms like unexplained weight loss, persistent cough, or skin changes to your doctor.',
  'Consult your physician before taking aspirin daily for preventive reasons to weigh risks.',
  'Do not double up on medication doses if you miss a scheduled dose; follow doctor or pharmacist guidelines.',
  'Keep your first aid kit stocked with sterile bandages, antiseptic wipes, thermometer, and pain relievers.',
  'Calibrate home health monitoring devices like blood pressure monitors according to manufacturer instructions.',
  'Refill essential prescription medications a week before running out to prevent missed doses.',
  'Avoid storing medications in the glove compartment of your car where temperatures fluctuate.',
  'Discuss any difficulty paying for or obtaining prescribed medicines with your doctor or pharmacist.',
  'Adjust your office chair so your feet rest flat on the floor and knees are at a 90-degree angle.',
  'Keep your computer screen directly at eye level to prevent neck flex and upper back strain.',
  'Maintain a neutral spine posture when sitting, avoiding slumping forward or arching back excessively.',
  'Position your keyboard and mouse so your forearms rest comfortably parallel to the desk floor.',
  'Stand up, stretch, and change posture for at least 2 minutes for every hour spent sitting down.',
  'Avoid holding your phone between your ear and shoulder; use hands-free ear-buds for longer calls.',
  'Hold your smartphone up closer to eye level to prevent text neck angle strain on your neck muscles.',
  'Bend your knees and lift with your legs when picking up heavy objects, keeping items close to your body.',
  'Avoid twisting your spine while carrying heavy loads; turn your whole body using your feet.',
  'Distribute weight evenly across both shoulders when carrying a backpack or heavy tote bag.',
  'Uncross your legs while sitting at a desk to promote healthy blood flow and pelvic alignment.',
  'Choose supportive footwear with adequate arch support for walking or standing for long periods.',
  'Use a lumbar support pillow behind your lower back when sitting for extended drives or desk work.',
  'Adjust your car seat so your arms are slightly bent while gripping the steering wheel effortlessly.',
  'Avoid sitting on a wallet in your back pocket, which can misalign your pelvis and irritate the sciatic nerve.',
  'Stretch your hip flexors regularly if you sit for long hours to prevent tight hips and low back pain.',
  'Perform chin tucks gently throughout the day to counteract forward head posture from screen use.',
  'Roll your shoulders backward and down periodically to release shoulder girdle tension.',
  'Ensure your desk work surface is at a comfortable height that prevents shrugging your shoulders.',
  'Use an ergonomic mouse or wrist rest if you experience fore-arm or wrist fatigue during typing.',
  'Alternate sides when carrying heavy grocery bags or shoulder bags to maintain spinal balance.',
  'Avoid sleeping on your stomach if you suffer from recurrent neck or low back pain.',
  'Place a pillow between your knees when sleeping on your side to keep your hips and spine aligned.',
  'Place a pillow under your knees when sleeping on your back to reduce pressure on your lower back.',
  'Avoid wearing high-heeled shoes daily as they alter your foot posture and strain calves and lumbar spine.',
  'Stretch your calf muscles and hamstrings daily to preserve lower body flexibility and joint motion.',
  'Maintain core muscle tone through exercises like planks to support stable spinal alignment.',
  'Step closer to objects before reaching for them to avoid overextending your upper back.',
  'Avoid standing with all your weight shifted onto one leg for prolonged periods.',
  'Check that your mattress provides firm support without causing pressure points at your shoulders and hips.',
  'Stretch your chest muscles by standing in a doorway and placing hands on the frame to counter hunching.',
  'Take micro-breaks every 30 minutes to roll shoulders, stretch neck, and squeeze shoulder blades.',
  'Choose a backpack with padded shoulder straps and a waist belt for heavy hiking or commuting loads.',
  'Avoid bending forward at the waist with straight legs when tying shoes or picking up lightweight items.',
  'Keep your computer monitor directly in front of you, not off to one side, to prevent neck rotation.',
  'Apply broad-spectrum sunscreen with SPF 30 or higher to exposed skin before going outdoors.',
  'Reapply sunscreen every 2 hours when outdoors, or more frequently if swimming or sweating.',
  'Wear a wide-brimmed hat and UV-blocking sunglasses to shield your face and eyes from direct sun.',
  'Seek shade during peak sunlight intensity hours between 10:00 AM and 4:00 PM.',
  'Moisturize your skin daily right after bathing while skin is still damp to lock in hydration.',
  'Use mild, fragrance-free cleansers to avoid stripping your skin of its natural protective oils.',
  'Avoid hot water showers that dry out skin; opt for warm water instead.',
  'Examine your skin monthly for new, growing, or changing moles using the ABCDE melanoma rule.',
  'Protect your skin from winter winds and cold temperatures by applying barrier creams and lip balm.',
  'Avoid tanning beds entirely, as UV radiation from sunlamps significantly raises skin cancer risk.',
  'Pat skin dry with a towel gently after washing instead of rubbing vigorously.',
  'Stay hydrated by drinking water to maintain skin elasticity and tissue health from within.',
  'Clean makeup brushes weekly with mild soap to prevent bacterial buildup and skin breakouts.',
  'Wear long sleeves and pants made of tightly woven fabric when outdoors in heavy sun or brush.',
  'Use insect repellent containing DEET or Picaridin in areas prone to mosquitoes and tick-borne diseases.',
  'Check your body for ticks after hiking or walking through woods or tall grass.',
  'Keep indoor humidity levels between 30% and 50% to prevent dry skin and respiratory irritation.',
  'Avoid harsh scrub exfoliants that cause microscopic tears in your skin barrier.',
  'Apply lip balm containing sunscreen SPF 15 or higher when spending time outside.',
  'Wash your face twice daily to remove environmental dirt, excess oil, and pollutants.',
  'Replace loofahs and bath sponges monthly as damp environments harbor bacteria.',
  'Wear rubber or vinyl gloves when using household chemical cleaners to protect your skin hands.',
  'Treat minor skin burns immediately by running cool tap water over the area for at least 10 minutes.',
  'Consult a dermatologist if you notice non-healing sores, persistent rashes, or changing moles.',
  'Avoid picking or squeezing acne lesions to prevent secondary bacterial infection and scarring.',
  'Use a humidifier in your bedroom during winter heating months to soothe dry skin and nasal passages.',
  'Apply aloe vera gel to calm mild sunburns and keep skin cool and hydrated.',
  'Choose non-comedogenic skin products and makeup if you are prone to clogged pores and breakouts.',
  'Keep household chemicals tightly sealed in original containers and stored in well-ventilated areas.',
  'Test new skin care products on a small patch of forearm skin first to check for allergic reactions.',
  'Wash clothes before wearing them for the first time to remove manufacturing chemical residues.',
  'Avoid prolonged exposure to damp clothing or wet socks to prevent fungal skin conditions.',
  'Protect your hands with insulating gloves during freezing weather to prevent frostbite and chapping.',
  'Clean air purifier filters regularly to reduce dust, pollen, and pet dander indoor allergens.',
  'Maintain clean household ventilation to reduce mold spore levels and protect lung health.',
  'Limit daily sodium intake to under 2,300 mg (roughly 1 teaspoon of salt) to support blood pressure.',
  'Avoid all forms of tobacco use, including smoking, chewing, and vaping, to protect heart and lungs.',
  'Know the warning signs of a stroke: sudden facial drooping, arm weakness, or speech difficulty (FAST).',
  'Monitor your waist circumference: keeping it under half your height reduces cardiovascular risk.',
  'Limit intake of refined carbohydrates to keep blood sugar stable and prevent insulin spikes.',
  'Engage in stress-reducing practices like deep breathing or meditation to lower resting blood pressure.',
  'Avoid sitting continuously for hours; stand up and move to stimulate leg venous circulation.',
  'Incorporate soluble fiber from oats, beans, and apples to help lower LDL (bad) cholesterol levels.',
  'Get your blood lipid panel (cholesterol) checked as recommended by your primary care doctor.',
  'Maintain a healthy body weight through consistent nutrition and regular physical activity.',
  'Limit alcohol consumption to moderate levels: no more than 1 drink daily for women, 2 for men.',
  'Eat foods rich in magnesium like spinach, almonds, and black beans to support nerve and muscle function.',
  'Stay current with blood pressure screenings; high blood pressure often has no noticeable symptoms.',
  'Avoid trans fats listed as partially hydrogenated oils on food labels to protect your blood vessels.',
  'Incorporate antioxidant-rich foods like berries, dark greens, and green tea into your diet.',
  'Avoid high-fructose corn syrup commonly found in sweetened beverages and processed foods.',
  'Take fast-acting simple carbohydrates like juice or glucose tablets if experiencing low blood sugar signs.',
  'Walk briskly for 30 minutes daily to raise HDL (good) cholesterol and support heart muscle health.',
  'Keep indoor air clean by avoiding smoking indoors and using proper exhaust fans when cooking.',
  'Monitor your pulse rate occasionally to check for irregular heart rhythms like atrial fibrillation.',
  'Eat cold-water fatty fish or flaxseed oil to maintain healthy triglyceride levels.',
  'Limit consumption of ultra-processed fast foods high in unhealthy fats and hidden sodium.',
  'Practice abdominal breathing: breathe in slowly through your nose and let your abdomen expand.',
  'Consult your physician if you experience leg swelling, persistent fatigue, or irregular heartbeat.',
  'Include garlic and onions in your cooking for natural sulfur compounds that support vascular health.',
  'Avoid heavy physical exertion suddenly without warming up, especially in freezing outdoor weather.',
  'Know your family medical history regarding heart disease, diabetes, and stroke to guide preventive care.',
  'Maintain regular meal schedules to help manage metabolic markers and blood sugar control.',
  'Stay hydrated to support proper blood volume and circulation throughout your cardiovascular system.',
  'Consult your doctor about taking vitamin D supplements if you have limited sunlight exposure.',
  'Avoid tight clothing around your waist or legs that restricts normal blood and lymphatic circulation.',
  'Engage in cardiovascular conditioning workouts like swimming, walking, or rowing regularly.',
  'Reduce consumption of processed deli meats to cut down on nitrates and excess salt intake.',
  'Rest adequately when recovering from viral illnesses to avoid overwhelming your cardiovascular system.',
  'Schedule regular routine health checkups even when feeling healthy to catch subtle conditions early.',
  'Practice slow, deep breathing exercises for 5 minutes daily to soothe your central nervous system.',
  'Spend 15 to 20 minutes outdoors in green spaces daily to boost mood and reduce stress hormones.',
  'Limit news consumption and screen time before bed to protect your mental well-being and sleep.',
  'Engage in daily physical movement to stimulate natural endorphins and reduce feelings of anxiety.',
  'Practice mindfulness by focusing fully on your current breathing and sensory surroundings.',
  'Take short mental rest breaks during intense work tasks to prevent cognitive fatigue and burnout.',
  'Keep a daily gratitude journal to foster positive mental focus and lower physiological stress.',
  'Protect your hearing by wearing ear protection in noisy environments over 85 decibels.',
  'Keep personal listening device volume below 60% and limit headphone use duration.',
  'Stay mentally active by solving puzzles, reading books, or learning new practical skills.',
  'Maintain good indoor air ventilation by cracking open windows when weather permits.',
  'Use a saline nasal spray or neti pot to clear nasal passages during allergy season.',
  'Avoid smoking near children or family members to protect them from harmful secondhand smoke.',
  'Wash bedding in hot water weekly to clear pollen and dust mites if you suffer from respiratory allergies.',
  'Stay active through lifelong hobbies like gardening, walking, or swimming to preserve physical vitality.',
  'Celebrate consistent, small daily health choices as key investments in your long-term longevity.',
];
