import 'package:flutter/material.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms of Service'),
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Terms of Service',
              style: TextStyle(
                color: theme.colorScheme.onSurface,
                fontSize: 26,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 6),
            Text(
              'Last updated: September 8, 2026',
              style: TextStyle(
                color: theme.colorScheme.onSurface.withValues(alpha: 0.6),
                fontSize: 13.5,
              ),
            ),
            const SizedBox(height: 24),

            // Important Medical Disclaimer Callout Box
            Container(
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                color: Colors.amber.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(16),
                border: Border.all(
                  color: Colors.amber.shade700.withValues(alpha: 0.4),
                ),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.warning_amber_rounded,
                    color: Colors.amber.shade800,
                    size: 24,
                  ),
                  const SizedBox(width: 14),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Important Medical Disclaimer',
                          style: TextStyle(
                            color: Colors.amber.shade900,
                            fontWeight: FontWeight.bold,
                            fontSize: 15,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          'MedNarrate is an AI-assisted tool designed solely for informational and educational purposes. MedNarrate is NOT a medical doctor, hospital, licensed healthcare provider, or emergency medical service. Never disregard professional medical advice or delay seeking medical treatment because of something generated by MedNarrate.',
                          style: TextStyle(
                            color: theme.colorScheme.onSurface.withValues(alpha: 0.85),
                            fontSize: 13.5,
                            height: 1.45,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 28),

            _buildSection(
              theme,
              title: '1. Acceptance of Terms',
              content:
                  'By accessing or using MedNarrate ("the Application"), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, please do not use the Application.',
            ),

            _buildSection(
              theme,
              title: '2. Description of the Application',
              content:
                  'MedNarrate provides plain-language summaries, laboratory value extraction, trend visualization, and RAG-based Q&A assistant features derived from uploaded medical reports. All summaries and AI explanations are advisory and intended to facilitate discussions between you and your healthcare team.',
            ),

            _buildSection(
              theme,
              title: '3. No Emergency Care or Diagnosis',
              content:
                  'The Application does not diagnose medical conditions, prescribe treatment plans, or provide emergency services. If you are experiencing a medical emergency, call your local emergency emergency response number (e.g., 911 or local equivalent) or visit the nearest emergency room immediately.',
            ),

            _buildSection(
              theme,
              title: '4. User Account & Security',
              content:
                  'You are responsible for maintaining the confidentiality of your authentication credentials and for restricting access to your device. You agree to notify us immediately if you suspect unauthorized access to your account.',
            ),

            _buildSection(
              theme,
              title: '5. Uploaded Reports & Data Responsibility',
              content:
                  'You retain ownership of all medical reports, prescriptions, and images uploaded to MedNarrate. You confirm that you have the right to upload such documents and that uploaded documents do not violate privacy rights of third parties.',
            ),

            _buildSection(
              theme,
              title: '6. AI Assistant & Limitation of Accuracy',
              content:
                  'Natural language processing and optical character recognition (OCR) systems can occasionally produce errors, hallucinations, or incomplete lab extractions. Always verify critical numerical laboratory ranges against the original lab documentation and with your physician.',
            ),

            _buildSection(
              theme,
              title: '7. Medication Reminders',
              content:
                  'Medication reminders scheduled within the Application are supplementary organizational aids. You remain fully responsible for managing your medication schedule as prescribed by your physician.',
            ),

            _buildSection(
              theme,
              title: '8. Limitation of Liability',
              content:
                  'To the maximum extent permitted by law, MedNarrate and its developers shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the Application.',
            ),

            _buildSection(
              theme,
              title: '9. Changes to Terms',
              content:
                  'We reserve the right to modify these Terms of Service at any time. Continued use of the Application after updates constitutes acceptance of the modified Terms.',
            ),

            const SizedBox(height: 30),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(ThemeData theme, {required String title, required String content}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 22),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              color: theme.colorScheme.onSurface,
              fontSize: 17,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: TextStyle(
              color: theme.colorScheme.onSurface.withValues(alpha: 0.75),
              fontSize: 14,
              height: 1.5,
            ),
          ),
        ],
      ),
    );
  }
}
